from dataclasses import dataclass

@dataclass
class DoomConstants:
    # Small enough to hardcode instead of writing another parser
    weapons = {
        'fist' : {
            'ammotype' : 0,
            'select'   : 'S_PUNCHUP',
            'deselect' : 'S_PUNCHDOWN',
            'ready'    : 'S_PUNCH',
            'fire'     : 'S_PUNCH1',
        },
        'pistol' : {
            'ammotype' : 1,
            'select'   : 'S_PISTOLUP',
            'deselect' : 'S_PISTOLDOWN',
            'ready'    : 'S_PISTOL',
            'fire'     : 'S_PISTOL1',
            'flash'    : 'S_PISTOLFLASH',
        },
        'shotgun' : {
            'ammotype' : 2,
            'select'   : 'S_SGUNUP',
            'deselect' : 'S_SGUNDOWN',
            'ready'    : 'S_SGUN',
            'fire'     : 'S_SGUN1',
            'flash'    : 'S_SGUNFLASH1',
        },
        'chaingun' : {
            'ammotype' : 1,
            'select'   : 'S_CHAINUP',
            'deselect' : 'S_CHAINDOWN',
            'ready'    : 'S_CHAIN',
            'fire'     : 'S_CHAIN1',
            'flash'    : 'S_CHAINFLASH1',
        },
        'rocket launcher' : {
            'ammotype' : 4,
            'select'   : 'S_MISSILEUP',
            'deselect' : 'S_MISSILEDOWN',
            'ready'    : 'S_MISSILE',
            'fire'     : 'S_MISSILE1',
            'flash'    : 'S_MISSILEFLASH1',
        },
        'plasma rifle' : {
            'ammotype' : 3,
            'select'   : 'S_PLASMAUP',
            'deselect' : 'S_PLASMADOWN',
            'ready'    : 'S_PLASMA',
            'fire'     : 'S_PLASMA1',
            'flash'    : 'S_PLASMAFLASH1',
        },
        'bfg 9000' : {
            'ammotype' : 3,
            'select'   : 'S_BFGUP',
            'deselect' : 'S_BFGDOWN',
            'ready'    : 'S_BFG',
            'fire'     : 'S_BFG1',
            'flash'    : 'S_BFGFLASH1',
        },
        'chainsaw' : {
            'ammotype' : 0,
            'select'   : 'S_SAWUP',
            'deselect' : 'S_SAWDOWN',
            'ready'    : 'S_SAW',
            'fire'     : 'S_SAW1',
        },
        'super shotgun' : {
            'ammotype' : 2,
            'select'   : 'S_DSGUNUP',
            'deselect' : 'S_DSGUNDOWN',
            'ready'    : 'S_DSGUN',
            'fire'     : 'S_DSGUN1',
            'flash'    : 'S_DSGUNFLASH1',
        },
    }

    sprite_names = [
        'TROO','SHTG','PUNG','PISG','PISF','SHTF','SHT2','CHGG','CHGF','MISG',
        'MISF','SAWG','PLSG','PLSF','BFGG','BFGF','BLUD','PUFF','BAL1','BAL2',
        'PLSS','PLSE','MISL','BFS1','BFE1','BFE2','TFOG','IFOG','PLAY','POSS',
        'SPOS','VILE','FIRE','FATB','FBXP','SKEL','MANF','FATT','CPOS','SARG',
        'HEAD','BAL7','BOSS','BOS2','SKUL','SPID','BSPI','APLS','APBX','CYBR',
        'PAIN','SSWV','KEEN','BBRN','BOSF','ARM1','ARM2','BAR1','BEXP','FCAN',
        'BON1','BON2','BKEY','RKEY','YKEY','BSKU','RSKU','YSKU','STIM','MEDI',
        'SOUL','PINV','PSTR','PINS','MEGA','SUIT','PMAP','PVIS','CLIP','AMMO',
        'ROCK','BROK','CELL','CELP','SHEL','SBOX','BPAK','BFUG','MGUN','CSAW',
        'LAUN','PLAS','SHOT','SGN2','COLU','SMT2','GOR1','POL2','POL5','POL4',
        'POL3','POL1','POL6','GOR2','GOR3','GOR4','GOR5','SMIT','COL1','COL2',
        'COL3','COL4','CAND','CBRA','COL6','TRE1','TRE2','ELEC','CEYE','FSKU',
        'COL5','TBLU','TGRN','TRED','SMBT','SMGT','SMRT','HDB1','HDB2','HDB3',
        'HDB4','HDB5','HDB6','POB1','POB2','BRS1','TLMP','TLP2',

        'TNT1', # invisible sprite                                 phares 3/9/98
        'DOGS', # killough 7/19/98: Marine's best friend :)
        'PLS1', # killough 7/19/98: first  of two plasma fireballs in the beta
        'PLS2', # killough 7/19/98: second of two plasma fireballs in the beta
        'BON3', # killough 7/11/98: evil sceptre in the beta version
        'BON4', # killough 7/11/98: unholy bible in the beta version
        'BLD2', # blood splats from Doom Retro, unsused in PrBoom+

        # 100 extra sprite names to use in dehacked patches
        'SP00', 'SP01', 'SP02', 'SP03', 'SP04', 'SP05', 'SP06', 'SP07', 'SP08', 'SP09',
        'SP10', 'SP11', 'SP12', 'SP13', 'SP14', 'SP15', 'SP16', 'SP17', 'SP18', 'SP19',
        'SP20', 'SP21', 'SP22', 'SP23', 'SP24', 'SP25', 'SP26', 'SP27', 'SP28', 'SP29',
        'SP30', 'SP31', 'SP32', 'SP33', 'SP34', 'SP35', 'SP36', 'SP37', 'SP38', 'SP39',
        'SP40', 'SP41', 'SP42', 'SP43', 'SP44', 'SP45', 'SP46', 'SP47', 'SP48', 'SP49',
        'SP50', 'SP51', 'SP52', 'SP53', 'SP54', 'SP55', 'SP56', 'SP57', 'SP58', 'SP59',
        'SP60', 'SP61', 'SP62', 'SP63', 'SP64', 'SP65', 'SP66', 'SP67', 'SP68', 'SP69',
        'SP70', 'SP71', 'SP72', 'SP73', 'SP74', 'SP75', 'SP76', 'SP77', 'SP78', 'SP79',
        'SP80', 'SP81', 'SP82', 'SP83', 'SP84', 'SP85', 'SP86', 'SP87', 'SP88', 'SP89',
        'SP90', 'SP91', 'SP92', 'SP93', 'SP94', 'SP95', 'SP96', 'SP97', 'SP98', 'SP99',
    ]

    sound_names = [
        None,
        'pistol',
        'shotgn',
        'sgcock',
        'dshtgn',
        'dbopn',
        'dbcls',
        'dbload',
        'plasma',
        'bfg',
        'sawup',
        'sawidl',
        'sawful',
        'sawhit',
        'rlaunc',
        'rxplod',
        'firsht',
        'firxpl',
        'pstart',
        'pstop',
        'doropn',
        'dorcls',
        'stnmov',
        'swtchn',
        'swtchx',
        'plpain',
        'dmpain',
        'popain',
        'vipain',
        'mnpain',
        'pepain',
        'slop',
        'itemup',
        'wpnup',
        'oof',
        'telept',
        'posit1',
        'posit2',
        'posit3',
        'bgsit1',
        'bgsit2',
        'sgtsit',
        'cacsit',
        'brssit',
        'cybsit',
        'spisit',
        'bspsit',
        'kntsit',
        'vilsit',
        'mansit',
        'pesit',
        'sklatk',
        'sgtatk',
        'skepch',
        'vilatk',
        'claw',
        'skeswg',
        'pldeth',
        'pdiehi',
        'podth1',
        'podth2',
        'podth3',
        'bgdth1',
        'bgdth2',
        'sgtdth',
        'cacdth',
        'skldth',
        'brsdth',
        'cybdth',
        'spidth',
        'bspdth',
        'vildth',
        'kntdth',
        'pedth',
        'skedth',
        'posact',
        'bgact',
        'dmact',
        'bspact',
        'bspwlk',
        'vilact',
        'noway',
        'barexp',
        'punch',
        'hoof',
        'metal',
        'chgun',
        'tink',
        'bdopn',
        'bdcls',
        'itmbk',
        'flame',
        'flamst',
        'getpow',
        'bospit',
        'boscub',
        'bossit',
        'bospn',
        'bosdth',
        'manatk',
        'mandth',
        'sssit',
        'ssdth',
        'keenpn',
        'keendt',
        'skeact',
        'skesit',
        'skeatk',
        'radio',
    ]

    mobj_flags = {
                1: 'SPECIAL',
                2: 'SOLID',
                4: 'SHOOTABLE',
                8: 'NOSECTOR',
               16: 'NOBLOCKMAP',
               32: 'AMBUSH',
               64: 'JUSTHIT',
              128: 'JUSTATTACKED',
              256: 'SPAWNCEILING',
              512: 'NOGRAVITY',
            0x400: 'DROPOFF',
            0x800: 'PICKUP',
           0x1000: 'NOCLIP',
           0x2000: 'SLIDE',
           0x4000: 'FLOAT',
           0x8000: 'TELEPORT',
          0x10000: 'MISSILE',
          0x20000: 'DROPPED',
          0x40000: 'SHADOW',
          0x80000: 'NOBLOOD',
         0x100000: 'CORPSE',
         0x200000: 'INFLOAT',
         0x400000: 'COUNTKILL',
         0x800000: 'COUNTITEM',
        0x1000000: 'SKULLFLY',
        0x2000000: 'NOTDMATCH',
        0x4000000: 'TRANSLATION1',
        0x8000000: 'TRANSLATION2',
    }
